# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jchittam.com server1 status
description: > # this means to ignore newlines until "baseurl:"
 The current status and past incidents.
baseurl: "/server-status" # the subpath of your site, e.g. /blog
url: "https://jchittam.github.io/server-status/"
permalink: :title/
full-url: "https://jchittam.github.io/server-status/" # the base hostname & protocol for your site


# CSS
sass:
  style: compressed

# Comments - Go to Disqus.com > sign up > get the short-name > insert it here
disqus-shortname: 

# Tracker
analytics: UA-83979019-1

# Form Settings
#
# Contact form can be enabled by getting an API key from https://getsimpleform.com/
simpleform-token: b6d4be9b039b666b3311e1ddcbfb577c

# Redirect users after submitting the form
redirect-to: https://jchittam.github.io/server-status/

# Site version
version: 0.9


# Post date background - This will change the background of the post date and tag ribbon according to the theme. If set to no default green background will be used. If yes then the theme color scheme is used.

change-date-bg: no


# Build settings
markdown: kramdown

include: [_pages] # Includes files inside _pages directory [Do not remove this]

author:
  name: jchittam.com server status
  image: ashwat.jpg # The author image will be shown on the header. Place this image in /images/ folder.
  about: Not much right now.
  facebook: 
  email: john@jchittam.com # mailto: is automatically added
  
gems: 
  - jekyll-seo-tag
  - jekyll-paginate
  
metadata:
 _posts:
  -name: "title"
   field:
     element: "text"
     label: "title"
  - name: "description"
    field:
      element: "text"
      label: "description"
  - name: "layout"
    field:
      element: "hidden"
      value: "post"
   - name: "date"
     field:
       element: "text"
       value: "CURRENT_DATETIME"
